DROP TABLE IF EXISTS hits;

CREATE TABLE hits(
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     app VARCHAR(64) NOT NULL,
                     uri VARCHAR(128) NOT NULL,
                     ip VARCHAR(65) NOT NULL,
                     created TIMESTAMP NOT NULL
);